services:
  mysql_db:
    image: mysql:8.0
    container_name: santex_academy_football_api_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASENAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}    
    ports:
      - "3306:3306" # Make sure it is the same port as DB_PORT in your .env file'
    volumes:
      - db_data:/var/lib/mysql
      #- ./docker/db:/docker-entrypoint-initdb.d 
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    build:
      context: ./fifa-backend
      dockerfile: Dockerfile
    container_name: santex_academy_backend
    depends_on:
      #- mysql_db
      mysql_db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./fifa-backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev

  frontend:
    build:
      context: ./fifa-frontend
      dockerfile: Dockerfile
    container_name: santex_academy_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./fifa-frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    command: npm run start -- --host 0.0.0.0
volumes:
  db_data: